### ISSUE TITLE
Rename `linkedin_username` to `linkedin_url`

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/cms-people#5]
LinkedIn accounts do not necessarily have a 'username' as such - this field should be renamed to `linkedin_url` and should be a URLField.

**Comment by danielsamuels** [comment]
That's not true, for example my username is 'danielsamuels': https://uk.linkedin.com/in/danielsamuels

**Comment by lewiscollard** [comment]
Isn't that optional though? That is why I think a URL makes more sense, as it handles both cases.

**Comment by jamesfoley** [comment]
Pretty sure some URLs arent a simple as swapping out the username, a URL would make more sense
